install:
  composer:
    early: 'skip'
    transform: |
      {
        "config": {
          "github-protocols": ["https"]
        },
        "preferred-install": {
          "oxid-esales/*": "source"
        },
        "require": {
          "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/session-authentication-component": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}"
        },
        "require-dev":{
          "oxid-esales/developer-tools": "{{ .Data.install.composer.dev_ref }}",
          "phpunit/phpunit": "^12.5"
        },
        "autoload-dev":{
          "psr-4":{
            "OxidEsales\\SessionAuthComponent\\Tests\\": "./vendor/oxid-esales/session-authentication-component/tests"
          }
        },
        "repositories": {
          "oxid-esales/session-authentication-component": {
            "type": "git",
            "url": "https://github.com/OXID-eSales/session-authentication-component.git"
          }
        }
      }

runscript:
  matrix:
    script: |
      [
        "session-auth:~/integration.sh --display-deprecations"
      ]
  composer:
    early: 'skip'
  session-auth:
    path: 'vendor/oxid-esales/session-authentication-component'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Session Auth Component ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
